language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.24"
install:
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla
script:
  - dzil authordeps --missing | cpanm --quiet --notest
  - dzil listdeps | cpanm --quiet --notest
  - prove -Ilib -r t/
